---
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: eventrouter
  namespace: monitoring
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app: eventrouter
  podMetricsEndpoints:
  - port: metrics
    path: "/metrics"

