{
 "title": "Sock-Shop Istio Performance",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "Chaos Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Chaos Experiments",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "none", "label": "CHAOS = TRUE" }
   ],
   "targets": [
    {
     "expr": "heptio_eventrouter_normal_total{reason=\"ChaosInject\",involved_object_name=~\"pod-cpu-hog.*\", involved_object_namespace=\"litmus\", involved_object_kind=\"ChaosEngine\"} - on () (heptio_eventrouter_normal_total{reason=\"PostChaosCheck\",involved_object_name=~\"pod-cpu-hog-.*\", involved_object_namespace=\"litmus\", involved_object_kind=\"ChaosEngine\"} OR on() vector(0))",
     "legendFormat": "catalogue-cpu-hog"
    },
    {
     "expr": "heptio_eventrouter_normal_total{reason=\"ChaosInject\",involved_object_name=~\"pod-memory-hog.*\", involved_object_namespace=\"litmus\", involved_object_kind=\"ChaosEngine\"} - on () (heptio_eventrouter_normal_total{reason=\"PostChaosCheck\",involved_object_name=~\"pod-memory-hog-.*\", involved_object_namespace=\"litmus\", involved_object_kind=\"ChaosEngine\"} OR on() vector(0))",
     "legendFormat": "orders-memory-hog"
    }
   ]
  },
  {
   "title": "Total Experiments Run",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 3, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "sum(litmuschaos_passed_experiments{namespace=\"litmus\",job=\"chaos-exporter\"}) + sum(litmuschaos_failed_experiments{namespace=\"litmus\",job=\"chaos-exporter\"})"
    }
   ]
  },
  {
   "title": "Passed Experiments",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 3, "x": 15, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "sum(litmuschaos_passed_experiments{namespace=\"litmus\",job=\"chaos-exporter\"})"
    }
   ]
  },
  {
   "title": "Failed Experiments",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 3, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "sum(litmuschaos_failed_experiments{namespace=\"litmus\",job=\"chaos-exporter\"})"
    }
   ]
  },
  {
   "title": "Queued Experiments",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 3, "x": 21, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(litmuschaos_awaited_experiments{namespace=\"litmus\",job=\"chaos-exporter\"})"
    }
   ]
  },
  { "title": "Orders Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "Orders QPS",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "ops", "label": "QPS (1 min)" }
   ],
   "targets": [
    {
     "expr": "sum(rate(istio_request_duration_milliseconds_count{destination_service_name=\"orders\",response_code=~\"2..\"}[1m])) * 100",
     "legendFormat": "2xx"
    },
    {
     "expr": "sum(rate(istio_request_duration_milliseconds_count{destination_service_name=\"orders\",response_code=~\"4.+|5.+\"}[1m])) * 100",
     "legendFormat": "4xx/5xx"
    },
    {
     "expr": "heptio_eventrouter_normal_total{reason=\"ChaosInject\",involved_object_name=~\"pod-memory-hog-.*\", involved_object_namespace=\"litmus\", involved_object_kind=\"ChaosEngine\"} - on () (heptio_eventrouter_normal_total{reason=\"PostChaosCheck\",involved_object_name=~\"pod-memory-hog-.*\", involved_object_namespace=\"litmus\", involved_object_kind=\"ChaosEngine\"} OR on() vector(0))",
     "legendFormat": "Chaos Period"
    }
   ]
  },
  {
   "title": "Orders latency",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 11 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(istio_request_duration_milliseconds_bucket{destination_service_name=\"orders\"}[1m])) by (destination_service_name, le))",
     "legendFormat": "99th quantile"
    },
    {
     "expr": "histogram_quantile(0.5, sum(rate(istio_request_duration_milliseconds_bucket{destination_service_name=\"orders\"}[1m])) by (destination_service_name, le))",
     "legendFormat": "50th quantile"
    },
    {
     "expr": "sum(rate(request_duration_seconds_sum{destination_service_name=\"orders\"}[1m])) / sum(rate(istio_request_duration_milliseconds_count{destination_service_name=\"orders\"}[1m]))",
     "legendFormat": "Mean"
    },
    {
     "expr": "heptio_eventrouter_normal_total{reason=\"ChaosInject\",involved_object_name=~\"pod-memory-hog-.*\", involved_object_namespace=\"litmus\", involved_object_kind=\"ChaosEngine\"} - on () (heptio_eventrouter_normal_total{reason=\"PostChaosCheck\",involved_object_name=~\"pod-memory-hog-.*\", involved_object_namespace=\"litmus\", involved_object_kind=\"ChaosEngine\"} OR on() vector(0))",
     "legendFormat": "Chaos Period"
    }
   ]
  },
  { "title": "Catalogue Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "Catalogue QPS",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "ops", "label": "QPS (1 min)" }
   ],
   "targets": [
    {
     "expr": "sum(rate(istio_request_duration_milliseconds_count{destination_service_name=\"catalogue\",response_code=~\"2..\"}[1m])) * 100",
     "legendFormat": "2xx"
    },
    {
     "expr": "sum(rate(istio_request_duration_milliseconds_count{destination_service_name=\"catalogue\",response_code=~\"4.+|5.+\"}[1m])) * 100",
     "legendFormat": "4xx/5xx"
    },
    {
     "expr": "heptio_eventrouter_normal_total{reason=\"ChaosInject\",involved_object_name=~\"pod-cpu-hog-.*\", involved_object_namespace=\"litmus\", involved_object_kind=\"ChaosEngine\"} - on () (heptio_eventrouter_normal_total{reason=\"PostChaosCheck\",involved_object_name=~\"pod-cpu-hog-.*\", involved_object_namespace=\"litmus\", involved_object_kind=\"ChaosEngine\"} OR on() vector(0))",
     "legendFormat": "Chaos Period"
    }
   ]
  },
  {
   "title": "Catalogue latency",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(istio_request_duration_milliseconds_bucket{destination_service_name=\"catalogue\"}[1m])) by (destination_service_name, le))",
     "legendFormat": "99th quantile"
    },
    {
     "expr": "histogram_quantile(0.5, sum(rate(istio_request_duration_milliseconds_bucket{destination_service_name=\"catalogue\"}[1m])) by (destination_service_name, le))",
     "legendFormat": "50th quantile"
    },
    {
     "expr": "sum(rate(request_duration_seconds_sum{destination_service_name=\"catalogue\"}[1m])) / sum(rate(istio_request_duration_milliseconds_count{destination_service_name=\"catalogue\"}[1m]))",
     "legendFormat": "Mean"
    },
    {
     "expr": "heptio_eventrouter_normal_total{reason=\"ChaosInject\",involved_object_name=~\"pod-cpu-hog.*\", involved_object_namespace=\"litmus\", involved_object_kind=\"ChaosEngine\"} - on () (heptio_eventrouter_normal_total{reason=\"PostChaosCheck\",involved_object_name=~\"pod-cpu-hog-.*\", involved_object_namespace=\"litmus\", involved_object_kind=\"ChaosEngine\"} OR on() vector(0))",
     "legendFormat": "Chaos Period"
    }
   ]
  },
  { "title": "Payment Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 } },
  {
   "title": "Payment QPS",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "ops", "label": "QPS (1 min)" }
   ],
   "targets": [
    {
     "expr": "sum(rate(istio_request_duration_milliseconds_count{destination_service_name=\"payment\",response_code=~\"2..\"}[1m])) * 100",
     "legendFormat": "2xx"
    },
    {
     "expr": "sum(rate(istio_request_duration_milliseconds_count{destination_service_name=\"payment\",response_code=~\"4.+|5.+\"}[1m])) * 100",
     "legendFormat": "4xx/5xx"
    }
   ]
  },
  {
   "title": "Payment latency",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 28 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(istio_request_duration_milliseconds_bucket{destination_service_name=\"payment\"}[1m])) by (destination_service_name, le))",
     "legendFormat": "99th quantile"
    },
    {
     "expr": "histogram_quantile(0.5, sum(rate(istio_request_duration_milliseconds_bucket{destination_service_name=\"payment\"}[1m])) by (destination_service_name, le))",
     "legendFormat": "50th quantile"
    },
    {
     "expr": "sum(rate(request_duration_seconds_sum{destination_service_name=\"payment\"}[1m])) / sum(rate(istio_request_duration_milliseconds_count{destination_service_name=\"payment\"}[1m]))",
     "legendFormat": "Mean"
    }
   ]
  },
  {
   "title": "Shipping Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 },
   "collapsed": true,
   "panels": [
    {
     "title": "Shipping QPS",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 14 },
     "yaxes": [
      { "format": "ops", "label": "QPS (1 min)" }
     ],
     "targets": [
      {
       "expr": "sum(rate(istio_request_duration_milliseconds_count{destination_service_name=\"shipping\",response_code=~\"2..\"}[1m])) * 100",
       "legendFormat": "2xx"
      },
      {
       "expr": "sum(rate(istio_request_duration_milliseconds_count{destination_service_name=\"shipping\",response_code=~\"4.+|5.+\"}[1m])) * 100",
       "legendFormat": "4xx/5xx"
      }
     ]
    },
    {
     "title": "Shipping latency",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 14 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum(rate(istio_request_duration_milliseconds_bucket{destination_service_name=\"shipping\"}[1m])) by (destination_service_name, le))",
       "legendFormat": "99th quantile"
      },
      {
       "expr": "histogram_quantile(0.5, sum(rate(istio_request_duration_milliseconds_bucket{destination_service_name=\"shipping\"}[1m])) by (destination_service_name, le))",
       "legendFormat": "50th quantile"
      },
      {
       "expr": "sum(rate(request_duration_seconds_sum{destination_service_name=\"shipping\"}[1m])) / sum(rate(istio_request_duration_milliseconds_count{destination_service_name=\"shipping\"}[1m]))",
       "legendFormat": "Mean"
      }
     ]
    }
   ]
  },
  {
   "title": "User Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 },
   "collapsed": true,
   "panels": [
    {
     "title": "User QPS",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 6 },
     "yaxes": [
      { "format": "ops", "label": "QPS (1 min)" }
     ],
     "targets": [
      {
       "expr": "sum(rate(istio_request_duration_milliseconds_count{destination_service_name=\"user\",response_code=~\"2..\"}[1m])) * 100",
       "legendFormat": "2xx"
      },
      {
       "expr": "sum(rate(istio_request_duration_milliseconds_count{destination_service_name=\"user\",response_code=~\"4.+|5.+\"}[1m])) * 100",
       "legendFormat": "4xx/5xx"
      }
     ]
    },
    {
     "title": "User latency",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 6 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum(rate(istio_request_duration_milliseconds_bucket{destination_service_name=\"user\"}[1m])) by (destination_service_name, le))",
       "legendFormat": "99th quantile"
      },
      {
       "expr": "histogram_quantile(0.5, sum(rate(istio_request_duration_milliseconds_bucket{destination_service_name=\"user\"}[1m])) by (destination_service_name, le))",
       "legendFormat": "50th quantile"
      },
      {
       "expr": "sum(rate(request_duration_seconds_sum{destination_service_name=\"user\"}[1m])) / sum(rate(istio_request_duration_milliseconds_count{destination_service_name=\"user\"}[1m]))",
       "legendFormat": "Mean"
      }
     ]
    }
   ]
  },
  {
   "title": "Frontend Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 37 },
   "collapsed": true,
   "panels": [
    {
     "title": "Frontend QPS",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 7 },
     "yaxes": [
      { "format": "ops", "label": "QPS (1 min)" }
     ],
     "targets": [
      {
       "expr": "sum(rate(istio_request_duration_milliseconds_count{destination_service_name=\"front-end\",response_code=~\"2..\"}[1m])) * 100",
       "legendFormat": "2xx"
      },
      {
       "expr": "sum(rate(istio_request_duration_milliseconds_count{destination_service_name=\"front-end\",response_code=~\"4.+|5.+\"}[1m])) * 100",
       "legendFormat": "4xx/5xx"
      }
     ]
    },
    {
     "title": "Frontend latency",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 7 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum(rate(istio_request_duration_milliseconds_bucket{destination_service_name=\"front-end\"}[1m])) by (destination_service_name, le))",
       "legendFormat": "99th quantile"
      },
      {
       "expr": "histogram_quantile(0.5, sum(rate(istio_request_duration_milliseconds_bucket{destination_service_name=\"front-end\"}[1m])) by (destination_service_name, le))",
       "legendFormat": "50th quantile"
      },
      {
       "expr": "sum(rate(request_duration_seconds_sum{destination_service_name=\"front-end\"}[1m])) / sum(rate(istio_request_duration_milliseconds_count{destination_service_name=\"front-end\"}[1m]))",
       "legendFormat": "Mean"
      }
     ]
    }
   ]
  },
  {
   "title": "Cart Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 38 },
   "collapsed": true,
   "panels": [
    {
     "title": "Cart QPS",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 8 },
     "yaxes": [
      { "format": "ops", "label": "QPS (1 min)" }
     ],
     "targets": [
      {
       "expr": "sum(rate(istio_request_duration_milliseconds_count{destination_service_name=\"carts\",response_code=~\"2..\"}[1m])) * 100",
       "legendFormat": "2xx"
      },
      {
       "expr": "sum(rate(istio_request_duration_milliseconds_count{destination_service_name=\"carts\",response_code=~\"4.+|5.+\"}[1m])) * 100",
       "legendFormat": "4xx/5xx"
      }
     ]
    },
    {
     "title": "Cart latency",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 8 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum(rate(istio_request_duration_milliseconds_bucket{destination_service_name=\"carts\"}[1m])) by (destination_service_name, le))",
       "legendFormat": "99th quantile"
      },
      {
       "expr": "histogram_quantile(0.5, sum(rate(istio_request_duration_milliseconds_bucket{destination_service_name=\"carts\"}[1m])) by (destination_service_name, le))",
       "legendFormat": "50th quantile"
      },
      {
       "expr": "sum(rate(request_duration_seconds_sum{destination_service_name=\"carts\"}[1m])) / sum(rate(istio_request_duration_milliseconds_count{destination_service_name=\"carts\"}[1m]))",
       "legendFormat": "Mean"
      }
     ]
    }
   ]
  }
 ]
}