apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: infrastructure
  namespace: flux-system
spec:
  #decryption:
  #  provider: sops
  #  secretRef:
  #    name: sops-gpg
  interval: 10m0s
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./infrastructure/local
  prune: true
  #postBuild:
  #  substitute: # TODO: for the moment, we don't use this to avoid messing with `kustomize.toolkit.fluxcd.io/substitute: disabled` in knative-operator
  #    gitops_branch: wip
  #    env: testing # May be broader scope
  #    # aws_acc_id: "TODO"
  #    # aws_region: eu-central-1
