name: Staging Auto-PR
on:
  push:
    branches: ['staging']

jobs:
  pull-request:
    name: Open PR to production
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      name: checkout

    - uses: repo-sync/pull-request@v2
      name: pull-request
      with:
        destination_branch: "production"
        pr_title: "Pulling ${{ github.ref }} into production"
        pr_body: "👑 *An automated PR*"
        pr_reviewer: "deas"
        pr_draft: true
        github_token: ${{ secrets.GITHUB_TOKEN }}
